[package]
name = "boids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy-inspector-egui = "0.19.0"
bevy_egui = "0.21.0"
bevy_prototype_debug_lines = "0.11"
rand = "*"
